stages:
  # download_data:
  #   cmd: python processed_data/preprocess_data.py
  #   deps:
  #   - processed_data/preprocess_data.py
  #   outs:
  #   - processd_data/reddit/ml_reddit_node.npy
  #   - processd_data/reddit/ml_reddit.csv
  #   - processd_data/reddit/ml_reddit.npy
  #   - processd_data/reddit/reddit.csv
  trains:
    cmd: python train.py
    deps:
    - train.py
    - data/test_features.csv
    - data/test_labels.csv
    - data/train_features.csv
    - data/train_labels.csv
    outs:
    - plot.png
    - metrics.txt
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
artifacts:
  scklearn-model:
    path: saved_model/model.pkl
    type: model
